version: "3.7"
services:
  web:
    image: docker.pkg.github.com/ikezoemakoto/web_db_press_3_sample/nginx
    ports:
      - "${HTTP_PORT}:80"
  app:
    image: docker.pkg.github.com/ikezoemakoto/web_db_press_3_sample/app
    volumes:
      - "./app/webroot:/app"
  database:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
  kvs:
    image: redis:6-alpine
volumes:
  mysql: